/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pharbers.kafka.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OssTask extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1182468546563980702L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OssTask\",\"namespace\":\"com.pharbers.kafka.schema\",\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"traceId\",\"type\":\"string\"},{\"name\":\"ossKey\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence jobId;
  @Deprecated public java.lang.CharSequence traceId;
  @Deprecated public java.lang.CharSequence ossKey;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OssTask() {}

  /**
   * All-args constructor.
   * @param jobId The new value for jobId
   * @param traceId The new value for traceId
   * @param ossKey The new value for ossKey
   */
  public OssTask(java.lang.CharSequence jobId, java.lang.CharSequence traceId, java.lang.CharSequence ossKey) {
    this.jobId = jobId;
    this.traceId = traceId;
    this.ossKey = ossKey;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jobId;
    case 1: return traceId;
    case 2: return ossKey;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jobId = (java.lang.CharSequence)value$; break;
    case 1: traceId = (java.lang.CharSequence)value$; break;
    case 2: ossKey = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'jobId' field.
   * @return The value of the 'jobId' field.
   */
  public java.lang.CharSequence getJobId() {
    return jobId;
  }

  /**
   * Sets the value of the 'jobId' field.
   * @param value the value to set.
   */
  public void setJobId(java.lang.CharSequence value) {
    this.jobId = value;
  }

  /**
   * Gets the value of the 'traceId' field.
   * @return The value of the 'traceId' field.
   */
  public java.lang.CharSequence getTraceId() {
    return traceId;
  }

  /**
   * Sets the value of the 'traceId' field.
   * @param value the value to set.
   */
  public void setTraceId(java.lang.CharSequence value) {
    this.traceId = value;
  }

  /**
   * Gets the value of the 'ossKey' field.
   * @return The value of the 'ossKey' field.
   */
  public java.lang.CharSequence getOssKey() {
    return ossKey;
  }

  /**
   * Sets the value of the 'ossKey' field.
   * @param value the value to set.
   */
  public void setOssKey(java.lang.CharSequence value) {
    this.ossKey = value;
  }

  /**
   * Creates a new OssTask RecordBuilder.
   * @return A new OssTask RecordBuilder
   */
  public static com.pharbers.kafka.schema.OssTask.Builder newBuilder() {
    return new com.pharbers.kafka.schema.OssTask.Builder();
  }

  /**
   * Creates a new OssTask RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OssTask RecordBuilder
   */
  public static com.pharbers.kafka.schema.OssTask.Builder newBuilder(com.pharbers.kafka.schema.OssTask.Builder other) {
    return new com.pharbers.kafka.schema.OssTask.Builder(other);
  }

  /**
   * Creates a new OssTask RecordBuilder by copying an existing OssTask instance.
   * @param other The existing instance to copy.
   * @return A new OssTask RecordBuilder
   */
  public static com.pharbers.kafka.schema.OssTask.Builder newBuilder(com.pharbers.kafka.schema.OssTask other) {
    return new com.pharbers.kafka.schema.OssTask.Builder(other);
  }

  /**
   * RecordBuilder for OssTask instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OssTask>
    implements org.apache.avro.data.RecordBuilder<OssTask> {

    private java.lang.CharSequence jobId;
    private java.lang.CharSequence traceId;
    private java.lang.CharSequence ossKey;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pharbers.kafka.schema.OssTask.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jobId)) {
        this.jobId = data().deepCopy(fields()[0].schema(), other.jobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.traceId)) {
        this.traceId = data().deepCopy(fields()[1].schema(), other.traceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ossKey)) {
        this.ossKey = data().deepCopy(fields()[2].schema(), other.ossKey);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OssTask instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pharbers.kafka.schema.OssTask other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.jobId)) {
        this.jobId = data().deepCopy(fields()[0].schema(), other.jobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.traceId)) {
        this.traceId = data().deepCopy(fields()[1].schema(), other.traceId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ossKey)) {
        this.ossKey = data().deepCopy(fields()[2].schema(), other.ossKey);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'jobId' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobId() {
      return jobId;
    }

    /**
      * Sets the value of the 'jobId' field.
      * @param value The value of 'jobId'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder setJobId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.jobId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jobId' field has been set.
      * @return True if the 'jobId' field has been set, false otherwise.
      */
    public boolean hasJobId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jobId' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder clearJobId() {
      jobId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'traceId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTraceId() {
      return traceId;
    }

    /**
      * Sets the value of the 'traceId' field.
      * @param value The value of 'traceId'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder setTraceId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.traceId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'traceId' field has been set.
      * @return True if the 'traceId' field has been set, false otherwise.
      */
    public boolean hasTraceId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'traceId' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder clearTraceId() {
      traceId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ossKey' field.
      * @return The value.
      */
    public java.lang.CharSequence getOssKey() {
      return ossKey;
    }

    /**
      * Sets the value of the 'ossKey' field.
      * @param value The value of 'ossKey'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder setOssKey(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ossKey = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ossKey' field has been set.
      * @return True if the 'ossKey' field has been set, false otherwise.
      */
    public boolean hasOssKey() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ossKey' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.OssTask.Builder clearOssKey() {
      ossKey = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public OssTask build() {
      try {
        OssTask record = new OssTask();
        record.jobId = fieldSetFlags()[0] ? this.jobId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.traceId = fieldSetFlags()[1] ? this.traceId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.ossKey = fieldSetFlags()[2] ? this.ossKey : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
