/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.confluent.ksql.avro_schemas;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class KsqlDataSourceSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4682843622048453961L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"KsqlDataSourceSchema\",\"namespace\":\"io.confluent.ksql.avro_schemas\",\"fields\":[{\"name\":\"CORP_NAME\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence CORP_NAME;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public KsqlDataSourceSchema() {}

  /**
   * All-args constructor.
   * @param CORP_NAME The new value for CORP_NAME
   */
  public KsqlDataSourceSchema(java.lang.CharSequence CORP_NAME) {
    this.CORP_NAME = CORP_NAME;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return CORP_NAME;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: CORP_NAME = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'CORP_NAME' field.
   * @return The value of the 'CORP_NAME' field.
   */
  public java.lang.CharSequence getCORPNAME() {
    return CORP_NAME;
  }

  /**
   * Sets the value of the 'CORP_NAME' field.
   * @param value the value to set.
   */
  public void setCORPNAME(java.lang.CharSequence value) {
    this.CORP_NAME = value;
  }

  /**
   * Creates a new KsqlDataSourceSchema RecordBuilder.
   * @return A new KsqlDataSourceSchema RecordBuilder
   */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder newBuilder() {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder();
  }

  /**
   * Creates a new KsqlDataSourceSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new KsqlDataSourceSchema RecordBuilder
   */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder newBuilder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder other) {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder(other);
  }

  /**
   * Creates a new KsqlDataSourceSchema RecordBuilder by copying an existing KsqlDataSourceSchema instance.
   * @param other The existing instance to copy.
   * @return A new KsqlDataSourceSchema RecordBuilder
   */
  public static io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder newBuilder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema other) {
    return new io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder(other);
  }

  /**
   * RecordBuilder for KsqlDataSourceSchema instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<KsqlDataSourceSchema>
    implements org.apache.avro.data.RecordBuilder<KsqlDataSourceSchema> {

    private java.lang.CharSequence CORP_NAME;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.CORP_NAME)) {
        this.CORP_NAME = data().deepCopy(fields()[0].schema(), other.CORP_NAME);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing KsqlDataSourceSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(io.confluent.ksql.avro_schemas.KsqlDataSourceSchema other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.CORP_NAME)) {
        this.CORP_NAME = data().deepCopy(fields()[0].schema(), other.CORP_NAME);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'CORP_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getCORPNAME() {
      return CORP_NAME;
    }

    /**
      * Sets the value of the 'CORP_NAME' field.
      * @param value The value of 'CORP_NAME'.
      * @return This builder.
      */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder setCORPNAME(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.CORP_NAME = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'CORP_NAME' field has been set.
      * @return True if the 'CORP_NAME' field has been set, false otherwise.
      */
    public boolean hasCORPNAME() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'CORP_NAME' field.
      * @return This builder.
      */
    public io.confluent.ksql.avro_schemas.KsqlDataSourceSchema.Builder clearCORPNAME() {
      CORP_NAME = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public KsqlDataSourceSchema build() {
      try {
        KsqlDataSourceSchema record = new KsqlDataSourceSchema();
        record.CORP_NAME = fieldSetFlags()[0] ? this.CORP_NAME : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
